version: "3"
services:

  db:
    restart: always
    image: postgres:10-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data

  web:
    build: .
    image: neetshin/halcyon
    restart: always
    env_file: .env
    ports:
      - "2800:2800"
    depends_on:
      - db
      - redis
    volumes:
      - .:/halcyon
